Add Datastore Data project API
vapor-community/google-cloud-kit pull request #19
Opened 2020-04-09 13:18 UTC by owainhunt

Implemented the 'main' datastore API, ie everything on this page: https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects

2020-04-09 19:38 UTC, Andrewangeta commented on Datastore/Sources/Data API/Models/Project API/Types/Query.swift
> +        startCursor: String? = nil) {
Just some spacing.

2020-04-09 19:38 UTC, Andrewangeta commented on Datastore/Sources/Data API/Models/Project API/Types/Query.swift
> +                 startCursor: String? = nil) {
Spacing/indentation

2020-04-09 19:39 UTC, Andrewangeta commented on Datastore/Sources/Data API/Models/Project API/Types/Query.swift
> +                 propertyFilter: PropertyFilter? = nil) {
Indentation

2020-04-09 19:39 UTC, Andrewangeta commented on Datastore/Sources/Data API/Models/Project API/Types/Query.swift
> +                 property: PropertyReference) {
Indentation

2020-04-09 19:39 UTC, Andrewangeta commented on Datastore/Sources/Data API/Models/Project API/Types/Query.swift
> +                 value: Value? = nil) {
Indentation

2020-04-09 19:39 UTC, Andrewangeta commented on Datastore/Sources/Data API/Models/Project API/Types/Query.swift
> +                 snapshotVersion: String? = nil) {
Indentation

2020-04-09 19:39 UTC, Andrewangeta commented on Datastore/Sources/Data API/Models/Project API/Types/Query.swift
> +                 queryString: String? = nil) {
indentation

2020-04-09 19:40 UTC, Andrewangeta commented on Datastore/Sources/Data API/Models/Project API/Types/Query.swift
> +                 value: Value? = nil) {
indentation

2020-04-09 19:40 UTC, Andrewangeta commented on Datastore/Sources/Data API/Models/Project API/Types/Value.swift
> +                 meaning: Int? = nil) {
Indentation

2020-04-09 19:41 UTC, Andrewangeta commented on Datastore/Sources/DatastoreClient.swift
> +    /// Initialize a client for interacting with the Google Cloud Storage API
Just some cloud storage verbiage in here.

2020-04-09 19:41 UTC, Andrewangeta commented on Datastore/Sources/DatastoreClient.swift
> +                                                   project: projectId)
Indentation

2020-04-09 19:42 UTC, Andrewangeta commented on Datastore/Sources/DatastoreConfig.swift
> +                                               project: nil)
Indentation

2020-04-09 19:42 UTC, Andrewangeta commented on Datastore/Sources/DatastoreConfig.swift
> +            case .cloudPlatform: return "https://www.googleapis.com/auth/cloud-platform"
Indentation

2020-04-09 19:46 UTC, Andrewangeta requested changes
This mostly looks good to me! Thanks for the PR :)
Other than the comments about indentation.

2020-04-09 19:49 UTC, Andrewangeta requested changes

2020-04-09 19:49 UTC, Andrewangeta commented on Datastore/Sources/Data API/API/ProjectAPI.swift
> +            return request.httpClient.eventLoopGroup.next().makeFailedFuture(error)
Also we can actually just use `request.eventLoop` for all the catch blocks in the requests and not have to ask the client anymore. Some of this in the cloud storage API was leftover and I'll raise a PR to clean it up soon.

2020-04-10 17:12 UTC, owainhunt commented
All fixed!

2020-04-10 17:24 UTC, Andrewangeta requested changes
Just a couple of indentations.

2020-04-10 17:24 UTC, Andrewangeta commented on Datastore/Sources/DatastoreClient.swift
> +        /// - `GoogleCloudStorageConfigurations` `project` property (optionally configured).
Should be `GoogleCloudDatastoreConfiguration`.

2020-04-10 17:24 UTC, Andrewangeta commented on Datastore/Sources/DatastoreClient.swift
> +                                                   project: projectId)
Small indentation here.

2020-04-10 18:57 UTC, owainhunt commented
Fixed.

2020-04-10 19:16 UTC, Andrewangeta commented
@Owainhunt thanks! And as a final sanity check, did you run locally to test the API works as expected?

2020-04-10 19:27 UTC, owainhunt commented
Just added something I didn't stage in the last commit. All good now - confirmed I've tested locally and all works as expected.

2020-04-10 19:28 UTC, Andrewangeta commented
Awesome!!

2020-04-10 19:28 UTC, Andrewangeta approved these changes

2020-04-10 19:41 UTC, merged